### ISSUE TITLE
Add an eye symbol behind the route name in the route activity if there is an ascend of type "watched", "heard" or "pissed" available 

### ISSUE THREAD

**Issue by paetz** [YacGroup/yacguide#101]
Currently, the ascend styles "seen", "visited", "heard" are not shown in the tourbook.
I would suggest to remove them. They don't have anything to do with a climbing guide or tourbook but rather with making public comments like on sandsteinklettern.de.

If such a style was imported from sandsteinklettern.de tourbook, we would simply omit it.

Edit: Conversation concluded. See adapted issue title.

**Comment by chrgernoe** [comment]
I agree that they are not very helpful but the app is a front-end for [sandsteinklettern.de](http://sandsteinklettern.de) and we should be somehow compatible with that. I would allow the import but skip them in the drop-down menu in our app so that the user cannot insert them.

**Comment by paetz** [comment]
@chrgernoe That's what I mean. Compatible means here: Do not crash on importing sandsteinklettern.de-tourbook. But we don't need to enter them into the yac-tourbook when importing an sandsteinklettern.de-tourbook.
Removing them from the skip-down-menu on entering a new ascend will improve UX a lot.

@Fabi2607 Other opinion? Otherwise, I'll just do it.

**Comment by chrgernoe** [comment]
In your implementation the ascend style would be empty after the import, right? It is okay, but you should at least show a message. Silently dropping ist not a nice behavior.

**Comment by paetz** [comment]
@chrgernoe No, I would just omit the corresponding ascend.
`for (ascend in ascendsToBeImported) {
    if (ascend.style == watched) {
        continue
   }
   db.insert(ascend)
}`
I would add a message like "Tourbook contains ascends of type "watched". These are omitted."

**Comment by chrgernoe** [comment]
Ok

**Comment by Fabi2607** [comment]
> @chrgernoe That's what I mean. Compatible means here: Do not crash on importing sandsteinklettern.de-tourbook. But we don't need to enter them into the yac-tourbook when importing an sandsteinklettern.de-tourbook.
> Removing them from the skip-down-menu on entering a new ascend will improve UX a lot.
> 
> @Fabi2607 Other opinion? Otherwise, I'll just do it.

I have actually used some and found them somewhat useful...

**Comment by paetz** [comment]
@Fabi2607 Ok, this sounds more like keeping them. How do you want them to be displayed? (Currently these „ascends“ are not shown anywhere)

**Comment by paetz** [comment]
Ok, I gonna rename the issue accordingly
