### ISSUE TITLE
Move selection of ascend style (now: drop-down) to it's own activity

### ISSUE THREAD

**Issue by paetz** [YacGroup/yacguide#105]
Because of too many possible ascend styles it's clearer to have an dedicated activity for selecting the style when entering a new ascend.

**Comment by paetz** [comment]
I've tested the new dev version with all 13 possible ascend types and I find it quiet ok meanwhile to keep the drop-down list instead of creating a separate activity for this. If nobody contradicts, I will close this issue as "Won't Do".

**Comment by chrgernoe** [comment]
I'm fine with this.
