### ISSUE TITLE
Consolidate ascend counts to a bit mask

### ISSUE THREAD

**Issue by paetz** [YacGroup/yacguide#110]
We should store the ascend data for route and rock table more efficiently:
`ascendsBitMask : Short = 0b000mlkjihgfedcba`
with
a : Boolean for solo, b : Boolean for Onsight etc.

Advantages:
- db storage decreases a lot
- better performance when using bit-wise operation
- less (error-prone) code

Add unit tests to verify that adding/deleting ascends updates the database correctly

**Comment by paetz** [comment]
Updating ascendsBitMask:
Adding an ascend: `ascendsBitMask |= marked1BitMask(styleId)`

Deleting an ascend:
```
rockAscends = db.getAscendsForRock(ascendToDelete.getRock())
rockFound = routeFound = false
for ascend in rockAscends:
    if ascendToDelete.styleId == ascend.StyleId:
        rockFound = true
        if ascendToDelete.getRoute() == ascend.getRoute():
            routeFound = true
            break
if not rockFound:
    rock.asendsBitMask &= marked0BitMask(styleId)
if not routeFound:
    route.ascendsBitMask &= marked0BitMask(styleId)
```

with e.g.
```
marked1BitMask(eAllesFrei) = 0b1000
marked0BitMask(eAllesFrei) = 0b0111
```

**Comment by chrgernoe** [comment]
You stated that you also want to implement unit tests but PR #117 does not contain any tests?

**Comment by paetz** [comment]
It was not as easy as I thought to get unit testing to work. So I postponed it.
    Am Montag, 10. Februar 2020, 10:56:03 MEZ hat Christian Sommer <notifications@github.com> Folgendes geschrieben:  
 
 
You stated that you also want to implement unit tests but PR #117 does not contain any tests?

**Comment by chrgernoe** [comment]
As soon as we released the first official version and when the app gets spreaded, there will also new feature requests or even PRs. For this we should implement test.
