### ISSUE TITLE
Repo clean-up

### ISSUE THREAD

**Issue by chrgernoe** [YacGroup/yacguide#114]
@paetz and @Fabi2607 
This is just a information for you that I cleaned-up the repository as agreed and removed the following files:
* `*.apk`
* `.DS_Store`
* `apk_signing_passwords.txt`
* `keystore.jks`

This reduced the size from about 40MB down to about 1MB. 

You need to clone/fork the repository again.

Hopefully I didn't screwed up things too much. :-) I backed up the repository before the operation and I will keep this backup for some time.

**Comment by Fabi2607** [comment]
Thanks, for doing this.

**Comment by paetz** [comment]
is this still open? Otherwise please close

**Comment by chrgernoe** [comment]
Not it's done.

**Comment by chrgernoe** [comment]
@vennekamp: You should also delete your fork and clone the repo again, if necessary.
