### ISSUE TITLE
Clean-up unnecessary escaped quoting characters during JSON download

### ISSUE THREAD

**Issue by chrgernoe** [YacGroup/yacguide#165]
The content of the [sandsteinklettern.de](sandsteinklettern.de) database is a mess regarding character encoding and escaped quoting characters. This especially leads to the fact that some escaped quoting characters show up in the app which is not nice and should be clean-up during download.

**Comment by JoergB2** [comment]
Was ist da jetzt genau das Problem? Ich weiß, das es ein paar Häßlichkeiten mit Anführungszeichen gibt, aber ich muss das konsequent escapen, da es sonst Murks und Sicherheitsprobleme mit den SQL-Ausdrücken gibt.

**Comment by chrgernoe** [comment]
@JoergB2 

* Genau, das ist ein Problem was vor allen Dingen entsteht, wenn man bei dir was editiert und dort schon Anführungszeichen enthalten sind. Wäre gut, wenn du das von deiner Seite verhinderst und idealerweise solche Sachen wie `\\"` mit beliebig vielen Backslashs generell aufräumst. Dann müssen wir das nicht in der App fixen.
* Eine zweite Unschönheit sind die unnötigen Unterstriche in manchen Gebietsnamen.
* Wenn man sich die JSON-Daten anschaut, dann gibt es dort auch Tabs, DOS-Zeilenumbrüche und einige nicht konsistent dekodierte tschechische Zeichen. 

Am meisten fallen die ersten beiden Punkte auf. Evtl. kannst du da ja mal was machen.

**Comment by JoergB2** [comment]
Hab jetzt mal noch einen Blick drauf geworfen und kommenta.php bereinigt. Ich hatte sinnloserweise den String aus der Datenbank escapt, bevor ich ihn als Vorlage in das Textfenster geschrieben habe, anstatt nur die Eingaben zu escapen.
Für weitere sinnlose Zeichen schicke mir bitte Beispiele.

**Comment by JoergB2** [comment]
Der JSON Import vom Tourenbuch scheint mit Sonderzeichen Probleme zu haben. Aus ö, ü , ä, ß werden komische Fragezeichen.

Weiterhin wird ignoriert, wenn der Begehungsstil "0" ist. Eigentlich sollte Begehungsstil 0 (=unbekannt) zwar gar nicht auftreten, kommt aber aufgrund von Murks im sandsteinklettern.de Import bei mir trotzdem vor. Weiß nicht, wie man damit am besten jetzt umgeht.

**Comment by chrgernoe** [comment]
Importierst du ein Tourenbuch von www.sandsteinklettern.de oder ein Tourenbuch, was du vorher aus dem YacGuide exportiert hast? Ich habe mir die Kodierung von einer JSON-Datei von deiner Webseite angeschaut. Die Datei ist als `ISO-8859-1` kodiert, was wahrscheinlich das Problem verursacht. Ich analysiere das Problem und gebe dir Bescheid. Vielleicht können wir das Problem in der App fixen. Am besten wäre wahrscheinlich, wenn du die JSON-Datei als `UFT-8` kodierte Datei rausschreibst. Dann sollte der Import auch kein Problem sein. 

Das zweite Problem könntest du temporär fixen, indem du in der JSON-Datei die Einträge entweder per Skript oder mit einem Editor auf einen definierten Wert setzt. Wir könnten für diesen Fall auch noch einen Begehungsstil _Unbekannt_ einführen. Was meinst du @paetz?

**Comment by JoergB2** [comment]
Ich importiere aus sandsteinklettern.de . Wenn ich mir die json-Datei mit dem Notepad Editor aus Windows XP ansehe, scheint es korrekt. Wenn ich weiß wie, dann ich natürlich auch versuchen serverseitig das Problem zu lösen. Kann ich diverse Skripte aus sandsteinklettern.de eigentlich hier irgendwo hochladen? Könnte evt. beim Verstehen von Problemen helfen.

**Comment by chrgernoe** [comment]
Entweder du schickst sie uns per Mail an yacgroup.dd@gmail.com oder du erstellst ein Git-Repo unter deinem Account und lädst dort die Dateien hoch. Falls du deinen Code nicht öffentlich zugänglich machen willst, erstellst du ein privates Repo und lädst @paetz und mich einfach ein. Die letzte Variante hat den Vorteil, dass man die komplette GitHub-Infrastrukur für Kommentare etc. nutzen kann. Du kannst im Prinzip auch deinen kompletten PHP-Code auf GitHub verwalten, wenn du willst.
Für das teilen von Codeschnipseln gibt es auch sogenannte Gists (oben rechst auf der Seite + -> New gist).

**Comment by paetz** [comment]
- Das Problem mit dem Zeichenformat beim Import hatte ich auch schon bemerkt ("?" statt Umlaute zb). Das habe ich damals schon nicht verstanden, da @JoergB2 eigentlich die php-Funktion `utf8_encode()` beim Erzeugen des Json-Tourenbuchs benutzt, wenn ich mich recht erinnere.

- Begehungsstil = 0: Ist das ein Überbleibsel von früheren Tourenbuch-Versionen oder ein Bug beim Erzeugen des Tourenbuchs serverseitig? Wenn es ein valider Wert ist, müssen wir ihn definitiv in die App mit einbauen.

**Comment by JoergB2** [comment]
Ich habe mal den Quellcode von tourenliste.php an yacgroup.dd@gmail.com geschickt. Vielleicht fällt euch ja was auf.
Begehungsstil=0 (=unbekannt, unklar) kommt vor, wenn Begehungsdaten nach sandsteinklettern.de importiert werden, der Importfilter den Begehungsstil aber nicht zuordnen kann. Ich habe da noch haufenweise solchen Krempel in meinen Daten, und kann das nur mühsam, Stück für Stück manuell bereinigen.

**Comment by chrgernoe** [comment]
Es gibt zwei Dinge, die mir in deinem Code auffallen:
* Du solltest das Format der JSON-Datei nicht selbst zusammenbauen. Warum das Rad nochmal neu erfinden, wenn es das schon gibt. Benutze einfach die Funktion `json_encode()` (https://www.php.net/manual/en/function.json-encode.php). Die aktuelle Implementierung sieht sehr abenteuerlich aus.
* Die Funktion `utf8_encode()` (https://www.php.net/manual/en/function.utf8-encode.php) wandelt `ISO-8859-1`- nach `UTF-8`-Strings. Bist du dir sicher, dass du aus deiner Datenbank immer Strings in der Kodierung bekommst? Wenn ich mein unvollständiges Tourenbuch von deiner Webseite als JSON exportiere, dann gibt es Einträge, wo die deutschen Umlaute kaputt sind und es gibt interessanterweise einen Eintrag, wo die Umlaute nicht kaputt sind. Das passiert, wenn ich die Datei als `ISO-8859-1` öffne. Schalte ich die Kodierung um, dann ist der eine Eintrag OK aber alle anderen Einträge kaputt. Das heißt für mich, dass die Strings in der Datenbank in verschiedenen Kodierungen vorliegen. Damit hat man natürlich komplett verloren. Man kann das dann nur korrigieren, indem dem den String in Bytes (ohne Kodierung) umwandelt, manuell die Bytes fixt und dann wieder z.B. nach `UTF-8` kodiert. Ich denke, dieses Problem entsteht irgendwo in dem PHP-Code wo du die HTML-Formulardaten in die Datenbank schreibst. Das Problem könnten wir zwar auf der App-Seite lösen, würde aber nicht die Ursache fixen. Das solltest du auf deiner Seite machen. Du musst quasi per Skript alle Strings in der Datenbank lesen, nach bekannten und falsch kodierten Zeichen suchen und diese fixen. Eine Alternative wäre, dass du für jeden String die Kodierung erkennst (z.B. mit https://www.php.net/manual/en/function.mb-detect-encoding.php), dann den Eintrag normalisierst und uns nur die normalisierte Variante zur Verfügung stellst. Behebt die Ursache aber auch nicht.

**Comment by JoergB2** [comment]
Räder erfinde ich gerne neu, weil es viel einfacher ist, als Anleitungen für Räder durchzulesen und zu verstehen. Ist eine Frage der Arbeitsökonomie und des Ansatz, die Anzahl verwendeter Funktionen einer Sprache auf ein Minimum zu beschränken. Die Dokumentation von json-Encode ist unklar, ich weiß nicht, an welcher Stelle ich das einsetzen sollte. 
Im weiteren habe ich mal die Struktur der Datenbank an yacgroup geschickt. Vielleicht gibt es ja da Auffälligkeiten. 
Kann ich mal ein Beispiel für unterschiedliche Codierung in der DB bekommen? Hab mich nie im Detail damit beschäftigt, wie die DB mit Texten umgeht; hab nur irgendwann festgestellt, dass sie sogar kyrillisch frisst und wieder ausspuckt.

**Comment by paetz** [comment]
Am besten, du erstellst dir mal ein privates (=unsichtbares) Repository hier auf Github, lädst alle deine php-Skripte hoch und lädst Christian und mich dazu ein. Dann können wir schauen, welche Stellen wir ggf. anfassen müssen, damit nur utf-8 in die DB kommt. Und dann müssten wir noch ein Skript schreiben, dass alle aktuellen DB-Daten zu utf-8 umwandelt, falls diese anders vorliegen.

**Comment by JoergB2** [comment]
Habe ich. Schaut mal unter https://github.com/JoergB2/sandsteinklettern

**Comment by chrgernoe** [comment]
Danke. Bitte ab jetzt dort Issues aufmachen und alle weiteren, nicht YacGuide-bezogenen, Diskussionen führen.

**Comment by chrgernoe** [comment]
@paetz: Have you an example where those escaped quoting characters show up in the app? I can't find any example anymore. Maybe @JoergB2 cleaned up the database.

**Comment by JoergB2** [comment]
Kann sein, dass ich irgendwas mal aufgeräumt habe.  Hier http://db-sandsteinklettern.gipfelbuch.de/weg.php?gipfelid=17126 ist die Spielwiese, wo man versuchen kann, fiese Zeichen einzubauen.
