### ISSUE TITLE
Absturz beim Versuch des Tourenbuch-Imports

### ISSUE THREAD

**Issue by JoergB2** [YacGroup/yacguide#166]
Wenn ich bei Tourenbuch auf Import gehe, und auf DURCHSUCHEN(*.JSON) klicke, stürzt das ab. TOURBOOK.JSON habe ich vorher mit Chrome heruntergeladen, sehe aber nicht, wo das hingespeichert worden ist.

**Comment by paetz** [comment]
Das ist ein exklusives Android 10 - Problem, da dort der angeforderte Root-Pfad nicht existiert.

- [ ] Fix: Select a more general default path for import filechooser.

**Comment by JoergB2** [comment]
Wie komme ich jetzt zu einer Version, wo das funktioniert? Wie mache ich ein Update?

**Comment by chrgernoe** [comment]
Ich muss baue heute Abend eine neue Version, die du dann per App-Store bekommst. Nutzt du die Entwicklerversion?

**Comment by JoergB2** [comment]
Hab gerade gesehen, dass es eine Entwicklerversion (Yacguide dev) gibt, und die zusätzlich installiert. Funzt in der Beziehung aber auch noch nicht, und tschechische Weg/Gipfel/Gebietsnamen auch nicht.

**Comment by chrgernoe** [comment]
@JoergB2: Wenn es dir nichts ausmacht ein Beta-Tester zu sein, dann installiere dir bitte die [Entwickler-Version](https://play.google.com/store/apps/details?id=com.yacgroup.yacguide.dev). Die habe ich vorhin hochgeladen und sollte morgen im App-Store verfügbar sein. Das geht leider nicht so schnell, da sie von Google immer noch überprüft wird. Was auch immer sie da machen. Die [offizielle Version](https://play.google.com/store/apps/details?id=com.yacgroup.yacguide) gibt es dann Ende der Woche.

**Comment by paetz** [comment]
@JoergB2 : App-Update geht über den Google Play Store. Dort kannst du unter "Meine Apps" deine Version updaten sobald sie von Google freigegeben wurde. Freigabe scheinbar grad in der Mache.
