### ISSUE TITLE
Anzeige 2. Sprache

### ISSUE THREAD

**Issue by JoergB2** [YacGroup/yacguide#167]
Gerade in den böhmischen Gebieten ist es wichtig, das nicht nur deutsche Bezeichnungen, sondern auch die tschechischen Namen für Gebiete, Gipfel und Wege angezeigt werden.

**Comment by paetz** [comment]
Der tschechische Name wird angezeigt, falls kein dt. Name vorliegt. Ich verstehe den Request, bin mir aber nicht sicher ob es übersichtlich möglich ist, zwei Namen pro List-Item anzuzeigen.

- [ ] To be evaluated: Zweitname in Kleinschrift unterhalb des Erstnamens anzeigen
