### ISSUE TITLE
Show summit statistic for each region

### ISSUE THREAD

**Issue by chrgernoe** [YacGroup/yacguide#170]
Check, if this causes significant performance issues.

**Comment by paetz** [comment]
Two potential problems:
- you will need to iterate over the whole tourbook and compare it with all routes of all rocks of all sectors in that region --> requires much computation time
- might look a bit inflated for regions with many rocks, e.g. "MyRegionInCountryX    (1234 / 2345)" and for long region names, the horizontal space might not be enough to display all these information

**Comment by paetz** [comment]
Regarding my second concern: Since regions are not multilingual, we may use the space below the name for displaying the statistics (that is reserved for the second name).
