### ISSUE TITLE
Migrate to AndroidX support library

### ISSUE THREAD

**Issue by chrgernoe** [YacGroup/yacguide#172]
The currently used support library version 28 is deprecated.

https://developer.android.com/jetpack/androidx/migrate

**Comment by paetz** [comment]
Haven't you merged the corresponding PR just recently?

**Comment by chrgernoe** [comment]
No. This was just the change that the App is compiled with a newer version of the, let's say, tool flow an libraries. This was necessary because in November, Google would no longer accept Apps compiled with version 28.

By the way. With version 29 we are still behind because the latest version is 30. This is the next step.
