### ISSUE TITLE
Implement "What's New" dialog

### ISSUE THREAD

**Issue by chrgernoe** [YacGroup/yacguide#177]
To inform users about new features or actions necessary in conjunction with new features, a dialog should be implemented that is shown once after an update and summarizes what's new. The same list should be deployed to the app store.

**Comment by chrgernoe** [comment]
@paetz: I will show this dialog only in the stable release otherwise we have to write release notes for each development version. In my eyes, this is not required. What do you think?

**Comment by paetz** [comment]
In that case, you would need to handle dev and stable version separately within the code. I believe, another approach is more sensible:
- We only create 1 dev version per milestone. After 1 or 2 weeks of testing this, we release a stable version of the same code base, so we'll have the same What's-New-content for both release types.
