### ISSUE TITLE
Checkbox for showing only projects in Rock activity

### ISSUE THREAD

**Issue by paetz** [YacGroup/yacguide#185]

**Comment by chrgernoe** [comment]
Would it not better to add a filter and search symbol to the top of the view next to the info symbol. The current approach doesn't scale, if more filters may implemented in the future.

**Comment by paetz** [comment]
No, #186 shall make filtering projects available region- and country-wise. I agree with your critics, but I see 2 disadvantages of that:
1. A search symbol would require a search dialog to open. In that case, you will not have the nice feature that the displayed rock list can update on each entered character.
2. The menu bar would become too full, especially when we merge the Back button someday. 

I would suggest to add a filter symbol once we add a third filter.

**Comment by chrgernoe** [comment]
> 1. A search symbol would require a search dialog to open. In that case, you will not have the nice feature that the displayed rock list can update on each entered character.

Probably there is UI feature to realize this anyway but I agree with the argument.

> 2. The menu bar would become too full, especially when we merge the Back button someday.

You are right, especially if the name is very long.

OK. Lets do it the way you implemented it.
