### ISSUE TITLE
Add projected rocks search to navigation in UpdatableTableActivity

### ISSUE THREAD

**Issue by paetz** [YacGroup/yacguide#186]

**Comment by chrgernoe** [comment]
Why would somebody need this feature? Most of the time, I would like to list the projects but not search for this. Would you please describe a reasonable usecase?

**Comment by paetz** [comment]
Imagine you have 50 projects. I find it pretty annoying to have them all listed in one table because:
1) It may hard to find only projects for a given sector. Imagine you want to visit Bielatal and would like to know, which projects you have there.
2) Different rocks (from different sectors) with the same name are not distinguishable in the current solution.

**Comment by chrgernoe** [comment]
Ok. I understand all your points but all your points describe a feature where you just want to show the projects for a certain activity which is partially implemented in #188. I still don't get the point of a search within the projects.

**Comment by paetz** [comment]
It does not mean search "within" the projects but rather search "for" projects "in" sector/region/country/globally.
