### ISSUE TITLE
By default select an invalid ascend style in the tourbook UI

### ISSUE THREAD

**Issue by chrgernoe** [YacGroup/yacguide#193]
At the moment, the default is `Solo`, which is a valid style. Hence, if the user forget to change it, there will be no warning and it may lead to an incorrect entry.

**Proposal:**
By default select an invald style and show e.g. the string `Select style`. If the entry is saved, this shall be checked and an error message shall be shown, if required.

**Comment by paetz** [comment]
I would add a style `Unknown` that corresponds to sandsteinklettern.de's style id 0. However, what do you think about route/summit coloring in that case? Regarding implementation, easiest approach would be to omit coloring in that case.

**Comment by chrgernoe** [comment]
As discussed offline:
* Ascends with style id 0 will be colored white in the tour book as well as in the database view.
* In the database view they will be marked with an exclamation symbol

**Comment by paetz** [comment]
I decided to go the way of coloring unknown ascends like followed-ascends. Reasons:
- less code
- preventing confusion regarding rock counting (Does Unknown count as a "real" rock ascend?)
- I guess in most cases, you don't enter a botched or projected route as Unknown. You have rather forgotten regarding lead or follow.
