### ISSUE TITLE
Tourbook import error for data set > 6000 entries

### ISSUE THREAD

**Issue by paetz** [YacGroup/yacguide#208]
Jacob T. filed a bug report that tourbook import from sandsteinklettern.de resulted in an error. He had a data et of > 6000 entries.
ToDo:
- Jacob may provide his tourbook for debugging
- report exact JSON or IO error for future bugs

**Comment by paetz** [comment]
The bug reporter does not want to share his json blob but told me that it worked in version 0.1.0. 
Hence, this issue should be cover only a more detailed error description for import/export.

**Comment by chrgernoe** [comment]
OK. There was a change in this code region with issue #64. I will check this and try to improve the error messages.
