### ISSUE TITLE
Do not select the rock search field automatically

### ISSUE THREAD

**Issue by chrgernoe** [YacGroup/yacguide#225]
There is feedback from one of our users who complains that the rock search field is automatically selected in the sector activity. This leads to the fact, that the keyboard comes up immediately and reduces the visible area of the app. Personally I agree with this complain and would like to change this. 

@paetz: What do you think?

**Comment by paetz** [comment]
I agree. However, I hope, it's not an Android version problem because on my phone (Android 9), the textfield's auto-focus seems to be off.

**Comment by chrgernoe** [comment]
It seems to depend on the Android version,
