### ISSUE TITLE
Change of style from e.g. solo to botch generates an invalid database entry

### ISSUE THREAD

**Issue by chrgernoe** [YacGroup/yacguide#227]
If a tour book entry e.g. with style _Solo_ is added and after saving, the style is changed to e.g. _Gesackt_, the entry is still coloured like a lead ascend (if enabled). It looks like there are two entries in the database because the entry can be deleted but the "eye" symbol is still there and shows an empty entry. The app crashes, if the delete button is pressed in the empty entry.
This doe not happen, if an entry is changed from e.g. _Solo_ to _Nachstieg_.

**Comment by paetz** [comment]
Cannot reproduce with the given description. Could you please provide a concrete list of steps?

**Comment by chrgernoe** [comment]
1.  Enter new ascend with style _Solo_ and a date and press OK to save the entry.
2. Edit the ascent, change the style to _Gesackt_ and save the entry.
3. Now, you should see the route marked as leaded ascend which is wrong.
4. Select the ascent and delete it. It deletes the entry, however the "eye" symbol show the entry is still there.
5. Select it and there should be an empty page.
6. Try to delete it which leads to an app crash.

**Comment by paetz** [comment]
- The problem occurs if you change ascend style to anything >= 9 (gesackt, zugesehen, ..., projekt).
- It does NOT invalidate the db, but only the ascend bit masks for route and rock.
- After fixing this, the only way to reset the invalid bit masks is tourbook export and import again right after that.

**Comment by paetz** [comment]
Problem is that the rock and route bitmasks are not updated accordingly on ascend deletion
