### ISSUE TITLE
Partner not accordingly updated if changing name and resuming PartnerActivity by pressing phone's back button

### ISSUE THREAD

**Issue by paetz** [YacGroup/yacguide#233]
Reproducible by:
1. add ascend with an existing partner
2. edit partners -> edit and save partner's name
3. resume to AscendActivity with phone`s back button --> partner's name has not changed in AscendActivity
4. edit partners --> partner is not selected anymore
5. resume to AscendActivity --> partner's name is now unknown (`???`)
6. if you add the partner again, you will have two partners (`???`, partner)

**Comment by chrgernoe** [comment]
I can confirm steps 1 to 4 with version `0.2.0`, `0.3.0` and `0.3.1`. However, the issue with the `???` can I only see with the current dev release `20210418`. In all other versions the partner is just not present in the list.
