### ISSUE TITLE
Add database reset

### ISSUE THREAD

**Issue by paetz** [YacGroup/yacguide#242]
For future bugs it might be helpful to give the user the opportunity to reset all databases in the app ("Auf Werkseinstellungen zurücksetzen").
Add a info dialog about the consequences (all data lost) and recommend a tourbook export.

ToDo:
- Add button to settings view (at the bottom) "Auf Werkseinstellungen zurücksetzen!
- Remove all database content (not only tourbook) on click (after user confirmation via dialog)
- Reset all custom settings (`SharedPreferences`) to their default values (see `res/values/setup.xml`)

**Comment by chrgernoe** [comment]
I also thought about this because right now you can uninstall the app and the database is still on the device. If you install the app again, everything is still there. It might be seen also as a feature but with this new reset feature, the user at least has the opportunity to delete the data.
