### ISSUE TITLE
As a user, I want to see comments to routes as well as my ascents below the route description

### ISSUE THREAD

**Issue by ckummer** [YacGroup/yacguide#250]
As a user, I want to see comments from other users as well as my ascents below the description. These should be separated into two sections and should be either collapsable or in tabs.

**Comment by paetz** [comment]
Having both below the route description could be pretty byzantine. Imagine, you have 3 ascents and 5 comments for one route.

To keep consistency with the other levels (sector, summit, ...), I would hide the route comments behind the info symbol.

However, having your ascent(s) below the route description could be neat. In that case, we should remove the TourbookAscend view and the link in the tourbook would point to the route description view. This has got the advantage that you can re-check the route description when watching your ascent in the tourbook.

Nevertheless, I see 2 problems here:
1. Where do you want to place the UI elements for editing/deleting one of your route's ascents?
2. While the tourbook entry of an ascent shows only region and summit as info, the TourbookAscend view shows region, sector and summit plus the czech equivalents. This info would not be displayed anymore.

**Comment by paetz** [comment]
1. UI elements similar to PartnersActivity
2. Keep TourbookAscend view but we can get rid of error-prone approach of indexing different ascents for the same route within TourbookAscend view.
