### ISSUE TITLE
Rock and route filters based on user comments

### ISSUE THREAD

**Issue by paetz** [YacGroup/yacguide#251]
It would be very helpful to have more filters that match expectations on comments, e.g.:
- Show me all routes with: 
-- quality >= "lohnend"
-- humidity >= "normal abtrocknend"
-- "VIIc" <= grade <= "IXa"
-- ...
- Show me all rocks with:
-- importance >= "lohnender Gipfel"

where we should use the arithmetic mean of the comments if there are more than one available.

The filters for routes must be combinable. Default for one filter is that all values are allowed.

ToDo:

Pre-requirements:
1. #257
2. #260
3. #265 
4. #255
5. #259
6. #256

Feature:
1. #268 
3. #270 
4. #271 
5. #272 
6. #273

**Comment by chrgernoe** [comment]
If we introduce a sub-menu, I would also move the search field to this sub-menu or maybe move the info button to the menu and add a search button instead.

**Comment by paetz** [comment]
...or maybe even better: leaving only sync/delete in the menu and creating a filter button next to the info button. This might be the most consistent solution but would necessitate a new separate filter view that contains all filters.

**Comment by paetz** [comment]
After experimenting a bit, it seems the easiest to have everything in an options menu. This means, every activity from country to route will have its own (specific) options menu:
- Country/Region/Sector: all items
- Rock: all without "Aktualisieren" and "Löschen"
- Route: all without "Aktualisieren", "Löschen" and "Felsen suchen"

The filters should be part of the dialog that is opening by clicking on "Felsen suchen" menu item (or "Wege suchen" (to be added), respectively). 
As a consequence, the filter spinners from rock and route activity become obsolete and can be replaced by the former checkbox "Nur offizielle Gipfel" and "Nur offizielle Wege", respectively.

If nobody complains, I will adapt the ticket description accordingly.

**Comment by chrgernoe** [comment]
> The filters should be part of the dialog that opens by clicking on "Felsen suchen" menu item (or "Wege suchen" (to be added), respectively).

I see two features here: 
* The first one is the combination of search and filter, as implemented right now. 
* The second feature is to just filter the view and this selection should be stored until it is changed again. So it would be possible to see always e.g. "Offizielle Gipfel" only.

> Open question: How to provide objective grade filtering?

My first idea was the implementation of a spinner but with a central configurable scale system. In this case the app would just translate the systems in each other. However, after thinking a bit more about this feature, I see the problem that the grade is a free text field in the database which makes the filtering not really reliable. I think, to make this feature really useful, we need support from the database side to make clear to which system the grade belongs to.
