### ISSUE TITLE
Pretty-print for tourbook export

### ISSUE THREAD

**Issue by paetz** [YacGroup/yacguide#252]
When exporting the tourbook, the user should be able to decide between rough ID-based export (for re-import on a different device e.g.) and pretty-print export (like a name-based .csv file that may not be imported again).

**Comment by chrgernoe** [comment]
The UI and the code should be prepared for further formats.

**Comment by gnottgen** [comment]
👍 I just did an export Today, but couldn't figure out how to link route information to the export (RouteID and StyleID are hard to understand without having access to the database)

Json itself would be ok, but a way to opt for CSV would also be cool.

**Comment by chrgernoe** [comment]
Ok. I will work on this next.
