### ISSUE TITLE
Display comment's authors

### ISSUE THREAD

**Issue by paetz** [YacGroup/yacguide#253]
There were several requests to display a comment's author as part of the comment.
To avoid a necessary database change (-> new field "author", e.g.), I would suggest to make the author's nick name part of the comment's text like
- "Geiler Weg (JoergB)"
- "JoergB: Geiler Weg"
Preferences or other suggestions?

**Comment by chrgernoe** [comment]
How do you want to implement that? Parse the user JSON every time you update the a sector and insert the it into the comment? Sounds not very nice but OK, if you don't want to change the database it seems the only way.

My preferred way would be the first one but we should visually make the authors name different from the rest of the comment. Maybe with italic letters.

**Comment by paetz** [comment]
No, Jörg must add the comment's author's name to the json dump (jsoncomment.php) that is downloaded when getting comments. I'll talk to him about this. Since this request is partly driven by him, I guess, he won't complain :)
