### ISSUE TITLE
Remove warnings and refactor

### ISSUE THREAD

**Issue by paetz** [YacGroup/yacguide#262]
- Remove warnings, e.g. deprecated APIs
- Rename all `Ascend...` stuff to `Ascent...`
- Migrate to view bindings since kotlin-android-extensions is deprecated
- Remove deprecated code
- `inline` where possible
- Summarize SQL macros that are often used, e.g. `VIA_ROUTES_REGION = "$VIA_ROUTES_ROCK $VIA_ROCKS_SECTOR $VIA_SECTORS_REGION"`
- Remove all `!!` occurrences by proper error handling
- Use separate string keys defined in `setup.xml` for SharedPreferences keys

**Comment by chrgernoe** [comment]
I already noticed that but first wanted to finish #213 because there will probably even more after the API change.
