### ISSUE TITLE
Proper update of selected rock list on resuming

### ISSUE THREAD

**Issue by paetz** [YacGroup/yacguide#265]
Subtask of #251 

Scenario: Searching projects or botches, selecting one and editing/deleting the corresponding ascent. On resuming to the project/botch list, the corresponding rock is still part of it since the list is not updated on resuming.

Problem: The projected/botched rock ids are transmitted to the SelectedRock view on creation and will hence not be updated on resuming.

Solution: Don't pass a list of rock ids to the activity but pass a search level (country, region, sector, rock), the corresponding id/name and do the database query as part of `displayContent()` depending on the search level. To get rid of code duplications, the `SelectedRockActivity` view should be removed while the filtering would be done directly in `RockActivity`.

**Comment by chrgernoe** [comment]
Please be careful if you do database queries on the UI process because this degrades the user experience because everything feels unresponsive. If such things are necessary, we should introduce a concept for the whole app to decouple the UI from the rest.

**Comment by paetz** [comment]
This is the current state in every db action. So this (probably bad habit) won't change with this issue.
