### ISSUE TITLE
Accelerate rock search 

### ISSUE THREAD

**Issue by paetz** [YacGroup/yacguide#276]
Full-text rock search may be accelerated by factor 10 if filtering is done in sql directly instead of filtering in Kotlin after the database request.

Drawback: We need to change the separator for german and czech names from `\u0000` to something else. I suggest the control sequence `\u001A` (= substitute control sequence).

Consequence for users: If a user gets this version update, sectors or rocks with german and czech names may not be decoded correctly. However, the user can fix this by simply synchronizing the sector again, so I think, it would be ok.

Worst case (the user does not update local database after version update): 
- sector and rock names are displayed with an unknown symbol and not perfectly formatted
- rock search will not work for 2nd name, e.g.: If name is `Turm X\0000Věž X`, the sql filtering may not find this object if searching `Věž`.

@chrgernoe Is it possible to popup a hint for the user to update his/her local database if he/she opens the app right after a version update (like the What'sNew dialog)?

**Comment by chrgernoe** [comment]
Yes, it is possible. We already have this mechanism implemented for the change log.

**Comment by paetz** [comment]
Hm, looks like, we need to hardcode this somehow like `if newVersion = 0.5: showInfo`. Maybe it's more feasible to manually add it to the release notes (at the top, bold typeface) to avoid trash in the code.
