### ISSUE TITLE
Convert table layouts to ListView

### ISSUE THREAD

**Issue by paetz** [YacGroup/yacguide#291]
For features like rock or route search we may need to display lists of thousands of elements.
TableLayouts like LinearLayout are pretty slow because they build and hold all elements at once.
ListView meanwhile only builds the elements that are currently in the user's view.

Since inheritance is not possible for Room database objects, we gonna need one ListAdapter for each database object (Country, Region, ...).

Subtasks:
- Convert country list to RecyclerView #302 
- Convert region list to RecyclerView #303 
- Convert sector list to RecyclerView #304 
- Convert rock list to RecyclerView #305 
- Convert route list to RecyclerView #306
- Convert partner list to RecyclerView #301 
- Convert region manager list to RecyclerView #313 
- Convert tourbook list to RecyclerView #314

**Comment by chrgernoe** [comment]
See also: Recycler View](https://developer.android.com/guide/topics/ui/layout/recyclerview).
