### ISSUE TITLE
Add pinning approach for countries

### ISSUE THREAD

**Issue by paetz** [YacGroup/yacguide#294]
If swiping to the right on a country list element a pinning icon should appear and the according country should be pinned to the top of the list.
- This must be stored in the SharedPreferences.
- Add a separator between pinned and unpinned countries (Maybe use an empty general item --> depending on #313)
https://code.tutsplus.com/tutorials/adding-swipe-gestures-to-recyclerviews--cms-32427

Do not forget the possibility to unpin again :)

**Comment by paetz** [comment]
Suggestion:
- add checkboxes in front of each country/region whether do be displayed or not (default: off = not selected for displaying)
- add a checkbox above the list like "nur ausgewählte Anzeigen" to decide if only checked objects shall be displayed or all (default: off = show all)

**Comment by chrgernoe** [comment]
This extra checkbox consumes additional space in the display. I would prefer a pinning approach where these items are just moved to the top of the list. As for example in the Theema app where you can pin conversations. Maybe this approach is somehow already supported with this `ListView` (#291).

**Comment by paetz** [comment]
... or do it the other way around: Swiping means archiving countries/regions. Archived elements may be accessible via a button below the list.

**Comment by chrgernoe** [comment]
I would not implement the archive stuff because the list is not so long.
