### ISSUE TITLE
Drop support for API version <26 (Android 8.0)

### ISSUE THREAD

**Issue by chrgernoe** [YacGroup/yacguide#322]
According to the Google Play Store statistics, we have only one device with Android 5.1 (API 22) and two devices on Android 8.1 (API 27). I guess this one device with Android 5.1 is not even in use anymore. Therefore, I suggest to drop the support for the API <26 (Android 8.0) because we already have some code the is limited by this lower API levels. 

@paetz: What do you think?
@JoergB2: As far as I know, the support for API 22 was kept only for you. Would it be OK for you to drop this support or do you still use this device?

**Comment by JoergB2** [comment]
Wo kann man die Statistik sehen? Was gewinnt man, wenn man die Kompatibilität aufgibt? Mein aktuelles Telefon ist Android 9 oder 10. Ich habe nie Yacguide auf 5.1 installiert.

**Comment by chrgernoe** [comment]
Die können wir nur sehen. OK, dann muss es noch jemanden anders geben der so einen Knochen hat. Was man verliert ist, dass Leute mir einem sehr alten Telefon die neuen Versionen nicht mehr installieren können. Gewinnen tut man ein Stück mehr Freiheit bei der Programmierung obwohl Google schon sehr weit rückwärtskompatibel ist.

**Comment by paetz** [comment]
I fully agree to dropping API levels < 26 if there is only one left. This guy can still use the old version if desired.
This change goes in the same direction as we introduced unit tests with #318 which require Java8 (= API level 26) anyhow.

**Comment by chrgernoe** [comment]
The Google Play Store statistics may not the golden reference because we also provide the app via F-Droid. However, we don't have any data about F-Droid but probably the statistic would not look much different.
