### ISSUE TITLE
Android back button does not update partner list in tour book entry

### ISSUE THREAD

**Issue by chrgernoe** [YacGroup/yacguide#356]
If a tour book entry is add/update and a partner was selected, only the arrow in the app updates the partner list in the tour book entry UI. If the android back button is used, the partner list is not updates.

@paetz: Shall we handle this as bug or feature?

**Comment by paetz** [comment]
This is intended, so that the phone's back button can act as a cancel button while the app's back button is the "OK" button. So if you want to implement this, it would be a feature.

**Comment by chrgernoe** [comment]
OK. Than let's consider as an feature.
