### ISSUE TITLE
App hangs forever, if internet connection gets lost during region update

### ISSUE THREAD

**Issue by chrgernoe** [YacGroup/yacguide#370]
If the user starts the region update and the internet connection gets lost, the progress dialog keeps there forever and will also not continue/disappear, if the connections comes back. This can be emulated, if he user puts the phone into flight mode.

**Comment by paetz** [comment]
Will be somehow fixed by #353

**Comment by paetz** [comment]
@chrgernoe Since #353 has just been merged, could you please re-check if that is a sufficient work-around for this issue?

**Comment by chrgernoe** [comment]
Yes, it is an acceptable solution. Thx.
