### ISSUE TITLE
Automatic build and deployment flow

### ISSUE THREAD

**Issue by chrgernoe** [YacGroup/yacguide#58]
There should be no binary files inside the repository. Especially the `.apk` file should be removed. The build and deployment of this file should be done by the CI service. 
A suggestion for a simple flow would be as follows:
* Use the CI to automatically build and deploy a development version every day from the master branch, if there was a commit/merge since the last run.
* For official releases the maintainer must create a release tag which than triggers the CI again. 

Official releases should follow the [semantic versioning schema](https://semver.org/).

Please ensure:
- compatibility down to Android 5.1 (--> build with API level 22)
- correct app signing (use the key from apk_signing_passwords.txt in the root directory)

**Comment by paetz** [comment]
@Fabian: Christian would like to implement this feature if you have not worked on it so far.

**Comment by chrgernoe** [comment]
@Fabi2607: I'm totally fine, if you have a solution in mind. I opened this issue yesterday after a discussion with @paetz but forgot to assign it to me.

**Comment by Fabi2607** [comment]
@chrgernoe feel free to do it. I just played around with it on: https://github.com/Fabi2607/yacguide/tree/gitignore-ci

If you want you can just take it as the starting point or ignore it completely
