### ISSUE TITLE
Make decision about license and add corresponding file

### ISSUE THREAD

**Issue by chrgernoe** [YacGroup/yacguide#69]
For an open-source project, I think there should always be a license. Just to avoid discussions and problems with contributors.

**Comment by Fabi2607** [comment]
Agreed.

I am a friend of permissive licenses like MIT oder ISC.

**Comment by chrgernoe** [comment]
I think it is a community project. Therefore I would prefer LGPL. I found a nice dicision maker for all the licenses out there: http://oss-watch.ac.uk/apps/licdiff/

**Comment by chrgernoe** [comment]
@paetz What do you think about this topic?

**Comment by paetz** [comment]
I'm not an expert in license stuff and don't actually care at all. I believe you take the right decission :)

**Comment by Fabi2607** [comment]
> I think it is a community project. Therefore I would prefer LGPL. I found a nice license differentiator: http://oss-watch.ac.uk/apps/licdiff/

Also fine by me. I will create a PR.
