### ISSUE TITLE
Summit marked green even if one route is marked as project only

### ISSUE THREAD

**Issue by chrgernoe** [YacGroup/yacguide#73]
This is a little bit confusing, if a summit that the user has not been climbed yet but one route is marked as projects, will be marked as climbed (green color).

**Comment by paetz** [comment]
The main problem here is that the Summit table in the database only offers a boolean for "climbed" or "not climbed". Changing the database structure would lead to incompatibilities.

**Comment by chrgernoe** [comment]
The information about the climbing style is stored in the tourbook, isn't it? What is the problem to evaluate this value and use it for the color?

**Comment by paetz** [comment]
In the Summit view, you would need to iterate over all ascends for every summit which is too mauch overhead.

**Comment by paetz** [comment]
I've talked with Fabian and we decided to adapt the database structure by making the bool "climbed" field to an int containing the ascend style (like in the Route table). This has to be done BEFORE we produce a first "official" binary by CI.

**Comment by paetz** [comment]
This is addressed by #89. Closed
