### ISSUE TITLE
Date for projects make no sense

### ISSUE THREAD

**Issue by chrgernoe** [YacGroup/yacguide#74]
If a route is marked as project, the date makes no sense and should not be evaluated. Especially in the tour book, if no date is specified, a 0 is shown what it is somehow confusing.

**Comment by paetz** [comment]
Doesn't it make sense to have an info when you added the project? And then you're like: "Oh, this is a very old project of mine!" 
I'd say, a date for this ascend type does not hurt and can be used sensibly.

**Comment by Fabi2607** [comment]
> Doesn't it make sense to have an info when you added the project? And then you're like: "Oh, this is a very old project of mine!"
> I'd say, a date for this ascend type does not hurt and can be used sensibly.

Agreed.

**Comment by chrgernoe** [comment]
Ok but we should at least force a date, if the user does not enter one or just by default fill the date field. This avoids a 0.0.0 in the tour book.

**Comment by paetz** [comment]
@chrgernoe Partly disagree. We should keep the „empty“ date 0.0.0 for Don‘t cares (like your primary request). But we might remove the „0.0.0“ string when displaying it as a tourbook entry or in the ascend view.

**Comment by chrgernoe** [comment]
Ok, sounds reasonable.
