### ISSUE TITLE
Implement map settings view

### ISSUE THREAD

**Issue by Fabi2607** [YacGroup/yacguide#79]
For #57 to provide a good user experience, the map should have few settings:

- management of downloaded map material
- progress for map download

**Comment by paetz** [comment]
What's the sense of this issue? I would couple the map stuff completely to the sync of the sectors. This means:
- No map management needed. A map is downloaded/removed/updated together with the according sector via the same button
- Process of map download is part of the process of the whole sector's download (to be implemented)
- offline/online switch does not make any sense at all to me

**Comment by chrgernoe** [comment]
To reduce the size, I would only download the map tiles of the sector. Similar to the maps at sandsteinklettern.de.

**Comment by Fabi2607** [comment]
> What's the sense of this issue? I would couple the map stuff completely to the sync of the sectors. This means:
> 
>     * No map management needed. A map is downloaded/removed/updated together with the according sector via the same button

Well, internally it still needs to do that management of the downloaded material. That should have been a bit clearer.

> 
>     * Process of map download is part of the process of the whole sector's download (to be implemented)

>     * offline/online switch does not make any sense at all to me

That would more or less come for free the way I map download will work internally...

**Comment by paetz** [comment]
@chrgernoe IMHO, this issue may be closed as Won't Do. Do you agree?

**Comment by paetz** [comment]
We will not add any map rendering data in the midterm to the app but instead rely on external map apps.
