### ISSUE TITLE
Implement database format version

### ISSUE THREAD

**Issue by chrgernoe** [YacGroup/yacguide#80]
To handle possible database format changes in the future, I propose to implement a format version for the database. With this feature it is possible to find out what database version is currently running and a conversion of the existing database is possible.

**Comment by paetz** [comment]
This issue can be closed. The AppDatabase has got a version (currently version 1). When changing the db structure, we'll need to increase this number and implement a so-called migration from old to new version.

**Comment by chrgernoe** [comment]
Can you remember with which PR the version was implemented? I just want to reference the issue number here.

**Comment by paetz** [comment]
This was already part of the very first implementation. So no PR to reference here.

**Comment by chrgernoe** [comment]
Ok
