### ISSUE TITLE
Add download information if a country, region or sector is empty

### ISSUE THREAD

**Issue by paetz** [YacGroup/yacguide#88]
Please add an information Toast if there were no remote objects to download when synchronizing a region/sector.

**Comment by paetz** [comment]
Recent agreement: If main db page, country or region is empty --> place download button in the middle of the screen

**Comment by chrgernoe** [comment]
Without asking the user whether he wants to start the download or not because with PR #144 the download is fast enough in case the user accidentally pushed the button.

**Comment by paetz** [comment]
> Without asking the user whether he wants to start the download or not because with PR #144 the download is fast enough in case the user accidentally pushed the button.

Can be done in a separate issue.

**Comment by chrgernoe** [comment]
Ok, I added a new issue #155 for that.
