### ISSUE TITLE
Change db format: More info on summit level

### ISSUE THREAD

**Issue by paetz** [YacGroup/yacguide#89]
Add more ascend information on summit and route level to enable more flexible name decoration

**Comment by paetz** [comment]
Note: You need to adapt the appearance of summits and routes when fixing this. 
Suggestion: Green for Lead, Cyan for Following (Green prevails if both apply). For bothes and projects an icon should be added to the summit/route name in each case.

**Comment by Fabi2607** [comment]
> Note: You need to adapt the appearance of summits and routes when fixing this.
> Suggestion: Green for Lead, Cyan for Following (Green prevails if both apply). For bothes and projects an icon should be added to the summit/route name in each case. No decoration for "Watched" needed.

This sounds like a very good compromise between our two original approaches!
